---
title: "Untitled"
author: "Kirsten Fuller"
date: "1/19/2022"
output: html_document
---
# SET WORKING DIRECTORY
```{r setup, include=FALSE}
rm( list = ls() ); gc( )

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Boise State/classes/2022_spring/eeb697_movement_ecol")
```


# PREP WORKSPACE
```{r, include = FALSE, message = FALSE}
# load necessary packages
# define packages
packages <- c("tidyverse", "dplyr", "tidyr", "gtools", "ggplot2", "lubridate", "reshape2", "plyr", "rgdal", "sp", "sf", "maptools", "raster", "amt", "FedData", "tiff", "terra")

# install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# load packages
invisible(lapply(packages, library, character.only = TRUE))
```


# LOAD Data
```{r, message = FALSE}
# pelican location data
pel_dat <- read.csv("data/brown_pelican_data.csv")

# pelican reference data
pel_dat_ref_dat <- read.csv("data/brown_pelican_reference_data.csv")

# load in the landcover data for the gulf of mexico
gom_shp <- st_read("data/gulf_shp/gulf-of-mexico-protraction-polygons.shp")

# load gulf depth data
gom_depth_shp <- st_read("data/gulf_depth_shp/w98e78n31s18_isobath_selected_5-4000m.shp") # what a terrible file name

# load marine species diversity data
spec_div <- terra::rast("data/global_marine_fish.tif")
```


# CHECK TABULAR DATA
```{r}
# PRIMARY DATA:
# check column names of pelican data
colnames(pel_dat)

# remove unnecessary columns and change col names to be more succinct
pel_dat_sub <- pel_dat %>%
# get rid of unnecessary columns
  dplyr::select(-c(visible, study.name, tag.local.identifier, sensor.type, individual.taxon.canonical.name))%>% 
# rename columns
  dplyr::rename(animal.id = individual.local.identifier,
                long = location.long,
                lat = location.lat)

# create time stamp column, year, month, and date columns
pel_dat_sub <- pel_dat_sub %>%
  dplyr::mutate(timestamp = lubridate::ymd_hms(pel_dat$timestamp, tz = "EST"))

pel_dat_sub <- pel_dat_sub %>%
  dplyr::mutate(year = as.numeric(format(pel_dat_sub$timestamp, format = "%Y")),
                month = as.numeric(format(pel_dat_sub$timestamp, format = "%m")),
                day = as.numeric(format(pel_dat_sub$timestamp, format = "%d")),
                week = lubridate::week(pel_dat_sub$timestamp))

# create a table to tally up data by year
count((pel_dat_sub$year)) # 2014 had the most data @ 18,861 points

# subset out just that year
pel_dat_14 <- pel_dat_sub %>%
  dplyr::filter(year == "2014")

# determine the number of individals included in the study in 2014
length(unique(pel_dat_14$animal.id)) # 13 individuals

# determine which week has the most animals
table(pel_dat_14$week, by = pel_dat_14$animal.id) # okay so 26, 27 and 28 look bad
# 20 and 21 look the best, with all 13 animals having data
# I'm going to pick 20

pel_dat_14_wk20 <- pel_dat_14 %>%
  dplyr::filter(week == "20")


# REFERENCE DATA:
# explore the reference data a bit. How many males and females are included in the study?
count(pel_dat_ref_dat$animal.sex) # 14 females and 16 males

# join the reference data to the week 20 daya
pel_dat_join <- left_join(pel_dat_14_wk20, pel_dat_ref_dat, by = "animal.id") 

# remove unnecessary columns
pel_dat_join_sub <- pel_dat_join %>%
  dplyr::select(-c(animal.taxon, deploy.on.date, deploy.off.date, animal.life.stage, animal.reproductive.condition, animal.ring.id, attachment.type, deployment.id, manipulation.type, study.site, tag.manufacturer.name, tag.mass, tag.readout.method, tag.id, duty.cycle))
```


# SPATIAL DEFINING
```{r}
# check if it has a defined coordinate system
st_crs(pel_dat_join_sub) # it does not, but I know it should be WGS84 from the reference file
st_crs(gom_shp) # NAD27
st_crs(gom_depth_shp) # Unknown datum based upon the Clarke 1866 ellipsoid 
crs(spec_div)

# the READ_ME file says the pelican data is WGS84, so I will have to define the crs as an object. The EPSG code for that is 4326
pel_crs = "EPSG:4326"

# then assign the data to that crs
pel_dat_sf <- sf::st_as_sf(pel_dat_join_sub, coords = c("long", "lat"),
                           crs = st_crs(pel_crs))

# COME BACK TO HERE TO GET PREDICTORS:
# match the pelican data to the species diversity data 
pel_dat_sf_trans <- pel_dat_sf %>%
  st_transform(pel_dat_sf, crs = crs(spec_div))

# extract data from raster


# CONTINUE TO TRANSFORM SHPFILES
# match the gom depth shape data to the gom shape file
gom_depth_shp_trans <- st_transform(gom_depth_shp, crs = st_crs(gom_shp))

```


# DEFINING TRACKS
```{r}
# define the tracks
pel_tracks <- amt::make_track(pel_dat_join_sub, .x = long, .y = lat, .t = timestamp,
                              animal.id, day, animal.sex,
                              crs = 4326)
# transform the data back to the crs that we want 
pel_tracks_trans <- amt::transform_coords(pel_tracks, pel_crs)

# summarize the data
amt::summarize_sampling_rate(pel_tracks)

# turn into a tibble list by grouping and nesting by individual animals:
pel_tracks_nested <- pel_tracks_trans %>%  amt::nest(data = -"animal.id")

# plot each individual's track
for( i in 1:dim(pel_tracks_nested)[1]){
  a <- as_sf_points(pel_tracks_nested$data[[i]] ) %>% 
    ggplot(.) + theme_bw(base_size = 17) +
    labs( title = paste0('individual =', pel_tracks_nested$animal.id[i]) ) +
#    geom_sf(data = NCA_Shape, inherit.aes = FALSE ) +
     geom_sf() 
  print(a)
} 
```


```{r}

```

