---
title: "Untitled"
output: html_document
date: '2022-02-27'
---

## Set Working Directory
```{r setup, include=FALSE}
rm( list = ls() ); gc( )

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Documents/Boise_State/classes/eeb697_movement_ecol")
```

## Prepare Workspace
```{r, include = FALSE, message = FALSE}
# load necessary packages
# define packages
packages <- c("tidyverse", "dplyr", "tidyr", "ggplot2", "lubridate", "plyr", "rgdal", "sp", "sf", "raster", "amt", "terra", "rasterVis", "glmmTMB", "circular", "ctmm")

# install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# load packages
invisible(lapply(packages, library, character.only = TRUE))
```

## Load Objects
```{r}
# tracks:
pel_tracks_thin <- read_rds("data/output/pel_tracks_thin")
class(pel_tracks_thin)

jens_data <- read_rds("data/trks.thin")

gom_shape <- st_read("data/output/gulf_shp_crop.shp")
```

## Analysis Prep
```{r}
get_crs(pel_tracks_thin) # EPSG 4326
crs_tracks <- get_crs(jens_data) # NAD83

pel_tracks_thin_trans <- amt::transform_coords(pel_tracks_thin, crs_to = crs_tracks)
get_crs(pel_tracks_thin_trans)
```

# Kernel Density Estimates and Minimum Convex Polygon
Using the thinned data, re sampled at a 60 minutes sampling rate. 

## Home Range Estimates
```{r}
ranges <- pel_tracks_thin_trans %>% 
  nest(data = -"animal.id") %>%
  mutate(
    # minimum convex polygon
    hr_mcp = map(data, ~ hr_mcp(., levels = c(0.5, 0.9))),
    # kernel density estimator
    hr_kde = map(data, ~ hr_kde(., levels = c(0.5, 0.9))),
    # also calculate the sample size for each individual
    n = map_int(data, nrow))  

# view
head(ranges)

# plot KDE:
kde_plot <- ranges %>%
  hr_to_sf(hr_kde, animal.id, n) %>%
  ggplot(.) +
  theme_bw(base_size = 17) + 
  geom_sf(gom_shape, mapping = aes(geometry = geometry), fill = "light blue") +
  geom_sf() +
  facet_wrap(~animal.id)

kde_plot

# plot MCP:
mcp_plot <- ranges %>%
  hr_to_sf(hr_mcp, animal.id, n) %>% 
  ggplot(.) +
  theme_bw(base_size = 17) + 
  geom_sf(gom_shape, mapping = aes(geometry = geometry), fill = "light blue") +
  geom_sf() +
  facet_wrap(~animal.id)

mcp_plot

# estimate home range area for 1 week
# 1) remove tracking data and 2) convert to long dataframe
hr_area <- ranges %>%  
  select( -data ) %>% 
  pivot_longer(hr_mcp:hr_kde, names_to = "estimator", 
               values_to = "hr" )
# view
hr_area

# The we calculate area for each method 
hr_area <- hr_area %>%  
  mutate( hr_area = map(hr, ~hr_area(.)) ) %>% 
  unnest( cols = hr_area )

# convert area in m^2 to area in km^2 
hr_area$area_km <- hr_area$area / 1e6
hr_area$area_km <- round(hr_area$area_km, digits = 5)

hr_area_df <- hr_area %>%
  select(-c(what, hr))

# plot home ranges
hr_plot <- hr_area %>%
  filter(level == 0.9) %>%
  ggplot(aes(y = area_km, x = as.character(animal.id), fill = estimator)) +
  geom_bar(position = "dodge", stat = "identity", color = "black", size = 0.4) +
  labs(title = "90% Home Range Areas Estimated - MCP vs. KDE", x = "animal id", y = "home range area (km^2)") +
  scale_fill_manual("estimator",values = c('black', 'gray')) + 
  theme_classic()

hr_plot

str(hr_area_df)
hr_area_df$animal.id <- as.factor(hr_area_df$animal.id)
hr_area_df$level <- as.factor(hr_area_df$level)

# box plot of data
hr_area_df_plot.9 <- hr_area_df %>%
  filter(level == 0.9) %>%
  ggplot() +
  geom_boxplot(aes(x = estimator, y = area_km)) +
  labs(title = "90% Home Range Estimation", x = "estimation method", y = "home range area (km^2)")

hr_area_df_plot.9  

hr_area_df_plot.5 <- hr_area_df %>%
  filter(level == 0.5) %>%
  ggplot() +
  geom_boxplot(aes(x = estimator, y = area_km)) +
  labs(title = "50% Home Range Estimation", x = "estimation method", y = "home range area (km^2)")
hr_area_df_plot.5
```

Based on this, it looks as if MCP consistently estimates smaller home ranges than kde. 

# Autocorrelated Kernel Density Estimation
```{r}
# We start by plotting points for each individual: you can choose which data set by uncommenting and commenting lines 151 and 152 respectively
# trks.breed %>% 
trks.thin %>%   
  ggplot(., aes( x = x_, y = y_, color = speed ) ) +
  theme_bw( base_size = 15 ) + 
  geom_point() +
  facet_wrap( ~territory, scales = "free" ) # note that I color code speed...what else could you color code?

# estimating ranges in CTMM

# variograms using ctmm
# We can use ctmm to explore the remaining autocorrelation in our data. Compare variograms for thinned and unthinned data for 1 individual choose an individual id:
i <- 2

# filter tracks to select that individual's data
t <- trks.thin %>% filter( id == i )
a  <- trks.breed %>% filter( id == i )

# convert to ctmm object
ctmm.t <- as_telemetry( t )
ctmm.a <- as_telemetry( a )

# estimate empirical variograms
svf.t <- variogram( ctmm.t )
svf.a <- variogram( ctmm.a )

# now plot them side by side
par(mfrow = c(2,1) )
plot(svf.t, fraction = 1, level = 0.95)
plot(svf.a, fraction = 1, level = 0.95 )
# that second plot took a long time on my computer....for efficiency in the class I'm sticking to the thinned data, moving forward.

# ALL individuals using ctmm
# Plot variograms for all individuals extract names for individuals first into an object
ids <- unique( trks.thin$territory )
# create objects to store results
svf.t <- list()
ctmm.t <- list()
# set plot parameters
par( mfrow = c(3,3))
# loop through all individuals 
for( i in 1:length(ids)){
  # print progress
  print( i )
  # extract data for individual i
  t <- trks.thin %>% filter( id == i )
  # convert to ctmm object and add to list
  ctmm.t[[i]] <- as_telemetry( t )
  # calculate empirical variograms:
  svf.t[[i]] <- variogram( ctmm.t[[i]] )
  # plot variograms for each individual
  plot( svf.t[[i]] )
}
# note how they are unique for each individual. This supports the authors suggestions to estimate unique movement models for each individual

# automate the process of estimating a suitable movement model for the observed data using the empirical variogram as a guide.      
# options are:
# "iid": for uncorrelated independent data,     
# "bm": Brownian motion, "ou": Ornstein-Uhlenbeck process,  
# "ouf": Ornstein-Uhlenbeck forage process,                  
# "auto": uses model selection with AICc to find bets model  
# these model choices have real consequences to inference    

# create and object to store results 
m.best <- list()
# loop through each individual
# this won't be fast...remember that we are estimating all possible movement models for each individual and then using AIC to pick a best model from the model choices we also plot the empirical variograms vs the model results.
for( i in 1:length(ids)){
  print( i )
  # use empirical variogram estimated in the previous step as a way of guiding the choice of movement model
  guess <- ctmm.guess(data = ctmm.t[[i]], variogram = svf.t[[i]],
                      interactive = FALSE )
  # here we actually compare among 6 movement model options and compare fit using AIC to select the top model
  m.best[[i]] <- ctmm.select( ctmm.t[[i]], guess, verbose = TRUE,
                              trace = 2 )
  # view summary output for model comparison for each individual
  print(summary( m.best[[i]] ))
}

# use individual names to replace those in the list:
names( m.best ) <- ids

# define plotting parameters:
par(mfrow = c(2,2))
# now compare top model choice against traditional KDE
for( i in 1:length(ids) ){
  # trace progress:
  print(i)
  # add basic IID model to model list
  m.best[[i]]$"IID isotropic" <- ctmm.fit( ctmm.t[[i]],
                                           ctmm(isotropic = TRUE) )
  # extract model name for top model
  an <- rownames(summary( m.best[[i]][1]))
  # plot best model
  ctmm::plot( svf.t[[i]], m.best[[i]][[1]], 
              main = paste( ids[i], an ) ) # best model
  # plot worst model
  ctmm::plot( svf.t[[i]], m.best[[i]]$"IID isotropic", 
              main = paste( ids[i], "IID" ) ) # worse model
}  
# Now that we have estimated top movement models for each individual we are ready to apply those models to our estimates of ranges. We also have an extra option to choose from we can weight points based on high utilization to correct the range estimate...refer to the manuscript or the vignettes for more details 

# Here we compare ranges from 3 options: 
# (1) top movement model weighted 
# (2) top movement model without weighing 
# (3) traditional kde no weighing

# we create objects to store output from our 3 options:
akde.uw <- list()
akde.w <- list()
kde.iid <- list()

# We loop through each individual to estimate ranges for each option:
for( i in 1:length(ids) ){
  print(i)
  # using the top movement model without weights
  akde.uw[[i]] <- ctmm::akde( ctmm.t[[i]], m.best[[i]][[1]] )
  # using the top movement model with weights
  akde.w[[i]] <- ctmm::akde( ctmm.t[[i]], m.best[[i]][[1]], 
                             weights = TRUE )
  # using the IID movement model without weights
  kde.iid[[i]] <- ctmm::akde( ctmm.t[[i]], m.best[[i]]$"IID isotropic" )
}

# plot estimate ranges comparing output for each option:
par(mfrow = c(3,2))
for( i in 1:length(ids) ){
  print(i)
  plot( ctmm.t[[i]], akde.w[[i]] )
  title( paste("Weighted best model", ids[i]) )
  plot( ctmm.t[[i]], akde.uw[[i]] )
  title("Unweighted best model")
  plot( ctmm.t[[i]], kde.iid [[i]])
  title("Traditional KDE" )
}

# Estimating AKDE using atm package                          
# We use amt package (talks to ctmm) to estimate AKDE for a single individual to check for computational efficiency

# define the individual id as an object at the start so you can easily change it and try new ones, without having to alter the rest of the code
i <- 2
# filter data
idv.thin <- trks.thin %>% filter( id == i )
# inspect details for the chosen animal
idv.thin

# start estimating traditional KDE model
f.t.iid <- amt::fit_ctmm( idv.thin, "iid" )
# check
summary( f.t.iid )

# now fit the model chosen as top model by ctmm
f.t.ou <- amt::fit_ctmm( idv.thin, "ou" )
# summary values
summary( f.t.ou )
# What is the run time for that individual?
# Answer:

# estimate ranges for that individual using the KDE (approach that assumes no autocorrelation (traditional KDE))
akde_iid <- idv.thin %>% 
  amt::hr_akde(., model = f.t.iid, #fit_ctmm(., "iid" ),
               levels = 0.95 )

#run the ou model
akde_ou <- idv.thin %>% 
  amt::hr_akde(., model = fit_ctmm(., "ou" ),
               levels = 0.95 )

# instead of manually choosing, we can do model selection for each individual to find the optimal way of dealing with the observed movement behavior and autocorrelation model selection
akde_auto <- idv.thin %>% 
  amt::hr_akde( ., model = fit_ctmm(., "auto" ),
                levels = 0.95 )

# estimate areas for each method
amt::hr_area( akde_ou ) 
amt::hr_area( akde_iid ) 
amt::hr_area( akde_auto )


# plot comparisons from the different data choices
ggplot() +
  theme_bw( base_size = 15 ) +
  # extract isopleths for AKDE estimates from model selection approach:
  geom_sf( data = hr_isopleths( akde_auto ),
           fill = "blue", col = "blue", size = 1 ) +
  # extract isopleths for ou model
  geom_sf( data = hr_isopleths( akde_ou ),
           fill = NA, col = "black", size = 3 ) +
  # extract isopleths for traditional kde:
  geom_sf( data = hr_isopleths( akde_iid ), 
           fill = NA, col = "grey", size = 2 ) +
  # add points of autocorrelated data
  # note that we turn them into sf points for plotting 
  # geom_sf( data = as_sf_points( subset( trks.breed, id == ind) ) ) +
  geom_sf( data = as_sf_points( subset( trks.thin, id == 2)), 
           col = "red" )
```


# Save Results
```{r}
# MCP:
# save home range area estimates
write_rds( hr_wk, "hr_wk") 
# save home range daily area estimates
write_rds( ci_wk, "ci_wk" )

# KDE:
# save home range area estimates
write_rds( hr_wk, "hr_wk") 
# save home range daily area estimates
write_rds( ci_wk, "ci_wk" )

# AKDE:
# we can save the movement model results
save( m.best,file="../ctmmresults.rda") # save where you want
#save range results for 3 home range options
save( akde.w,file="../ctmm_akde_w.rda")
save( akde.uw,file="../ctmm_akde_uw.rda")
save( kde.iid,file="../ctmm_akde_iid.rda")
#save range for individual estimated using atm
write_rds( akde_auto, "akde_auto")
#save range for al individuals estimated with ctmm
write_rds( akde.w, "weighted_akdes" )
#save workspace if in progress
save.image( 'AKDEresults.RData' )
```

